# Generated by Django 4.1.7 on 2023-03-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_alter_tweet_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
