# Generated by Django 4.1.7 on 2023-03-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_alter_tweet_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repost',
            name='source',
        ),
        migrations.AddField(
            model_name='repost',
            name='repost_tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='tweet.tweet'),
        ),
        migrations.AddField(
            model_name='repost',
            name='source_tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='tweet.tweet'),
        ),
    ]
