# Generated by Django 4.1.7 on 2023-04-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_trend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trend',
        ),
    ]
