# Generated by Django 4.2.1 on 2023-05-23 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 9, 29, 42, 545597)),
        ),
    ]
