# Generated by Django 4.1.7 on 2023-04-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trend',
            options={'ordering': ['-tweet_count']},
        ),
        migrations.RenameField(
            model_name='trend',
            old_name='tweetCount',
            new_name='tweet_count',
        ),
    ]
