# Generated by Django 4.1.7 on 2023-03-20 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'replies'},
        ),
    ]
