# Generated by Django 4.1.7 on 2023-03-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0002_alter_reply_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'replie'},
        ),
    ]
