# Generated by Django 4.1.7 on 2023-03-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0004_reply_tweet_alter_reply_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='atachement',
            new_name='attachement',
        ),
    ]
