# Generated by Django 4.1.7 on 2023-03-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0005_rename_atachement_reply_attachement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='attachement',
            field=models.ImageField(blank=True, null=True, upload_to='atachements/'),
        ),
    ]
